import {useCallback,useEffect,useState} from "react";
import {ChevronLeft,ChevronRight,Eye,RefreshCw,Users} from "lucide-react";
import {completeApplicantTalentPoolReview,fetchApplicantTalentPool,fetchApplicantTalentPoolAnalytics,fetchApplicantTalentPoolOptions,patchApplicantTalentPoolMembership,removeApplicantFromTalentPool,restoreApplicantToTalentPool,scheduleApplicantTalentPoolReview,type ApplicantTalentPoolAnalytics,type ApplicantTalentPoolItem,type ApplicantTalentPoolOptions,type ApplicantTalentPoolPriority,type ApplicantTalentPoolQuery,type ApplicantTalentPoolReviewStatus} from "../../services/api";

const EMPTY:ApplicantTalentPoolOptions={categories:[],roles:[],skills:[],technicalExperienceLevels:[],tags:[],priorities:["normal","medium","high"],ownerIds:[],countries:[],cities:[],positionTracks:[],positionTypes:[],recruitmentStatuses:[],reviewStatuses:[],sortFields:[]};
const DEFAULT:ApplicantTalentPoolQuery={active:"true",page:1,limit:25,sortBy:"addedAt",sortOrder:"desc"};
const idOf=(x:ApplicantTalentPoolItem)=>x._id||x.id||x.applicantId||"";
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString():"—";
const cap=(v?:string)=>v?v.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase()):"—";

export function ApplicantTalentPoolDashboard({onOpenApplicant}:{onOpenApplicant?:(id:string)=>void|Promise<void>}){
  const [query,setQuery]=useState<ApplicantTalentPoolQuery>(DEFAULT); const [search,setSearch]=useState("");
  const [talent,setTalent]=useState<ApplicantTalentPoolItem[]>([]); const [pagination,setPagination]=useState({page:1,limit:25,total:0,pages:0});
  const [options,setOptions]=useState<ApplicantTalentPoolOptions>(EMPTY); const [analytics,setAnalytics]=useState<ApplicantTalentPoolAnalytics|null>(null);
  const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [r,o,a]=await Promise.all([fetchApplicantTalentPool(query),fetchApplicantTalentPoolOptions(),fetchApplicantTalentPoolAnalytics()]);setTalent(r.talent);setPagination(r.pagination);setOptions(o);setAnalytics(a);}catch(e){setError(e instanceof Error?e.message:"Unable to load Talent Pool.");}finally{setLoading(false);}},[query]);
  useEffect(()=>{void load();},[load]);
  const setFilter=(k:keyof ApplicantTalentPoolQuery,v:unknown)=>setQuery(q=>({...q,[k]:v||undefined,page:1}));
  const act=async(fn:()=>Promise<unknown>)=>{try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:"Talent Pool action failed.");}};
  const edit=async(x:ApplicantTalentPoolItem)=>{const id=idOf(x);if(!id)return;const roles=window.prompt("Roles (comma separated):",(x.talentPool.roles||[]).join(", "));if(roles===null)return;const owner=window.prompt("Owner id:",x.talentPool.ownerId||"");if(owner===null)return;const priority=window.prompt("Priority: normal, medium, high",x.talentPool.priority||"normal") as ApplicantTalentPoolPriority|null;if(!priority)return;await act(()=>patchApplicantTalentPoolMembership(id,{roles:roles.split(",").map(v=>v.trim()).filter(Boolean),ownerId:owner.trim(),priority}));};
  const schedule=async(x:ApplicantTalentPoolItem)=>{const id=idOf(x);if(!id)return;const v=window.prompt("Next review date/time (YYYY-MM-DDTHH:mm):",x.talentPool.nextReviewAt?new Date(x.talentPool.nextReviewAt).toISOString().slice(0,16):"");if(!v)return;const d=new Date(v);if(Number.isNaN(d.getTime()))return window.alert("Invalid date/time");await act(()=>scheduleApplicantTalentPoolReview(id,d.toISOString()));};
  const cards=[["Active Talent",analytics?.summary.activeMembers||0],["High Priority",analytics?.summary.highPriority||0],["Reviews Due",analytics?.summary.reviewDue||0],["Overdue",analytics?.summary.reviewOverdue||0],["Added 30 Days",analytics?.summary.recentlyAdded30||0],["Categories",analytics?.summary.categoriesRepresented||0]];
  return <div className="space-y-5">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Applicant Management</div><h2 className="mt-1 text-2xl font-bold text-slate-900">Talent Pool</h2><p className="mt-1 text-sm text-slate-500">Retain, categorize, search and revisit suitable Applicants without duplicating Applicant data.</p></div><button onClick={()=>void load()} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold"><RefreshCw className="h-4 w-4"/>Refresh</button></div></section>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{cards.map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-xs font-semibold uppercase text-slate-500">{l}</div><div className="mt-2 text-2xl font-bold">{v}</div></div>)}</section>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-3 border-b p-4 md:grid-cols-3 xl:grid-cols-6">
      <div className="flex gap-2 md:col-span-2"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setFilter("q",search.trim())} placeholder="Search name, role, skill..." className="w-full rounded-xl border px-3 py-2 text-sm"/><button onClick={()=>setFilter("q",search.trim())} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Search</button></div>
      <select value={query.active||"true"} onChange={e=>setFilter("active",e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="true">Active</option><option value="false">Removed</option><option value="all">All</option></select>
      <select value={query.categoryId||""} onChange={e=>setFilter("categoryId",e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="">All Categories</option>{options.categories.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select>
      <select value={query.priority||""} onChange={e=>setFilter("priority",e.target.value as ApplicantTalentPoolPriority)} className="rounded-xl border px-3 py-2 text-sm"><option value="">All Priorities</option>{options.priorities.map(v=><option key={v} value={v}>{cap(v)}</option>)}</select>
      <select value={query.reviewStatus||""} onChange={e=>setFilter("reviewStatus",e.target.value as ApplicantTalentPoolReviewStatus)} className="rounded-xl border px-3 py-2 text-sm"><option value="">All Review States</option>{options.reviewStatuses.map(v=><option key={v} value={v}>{cap(v)}</option>)}</select>
    </div>
    {error&&<div className="m-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    {loading?<div className="p-10 text-center text-sm text-slate-500">Loading Talent Pool...</div>:talent.length===0?<div className="p-10 text-center text-sm text-slate-500"><Users className="mx-auto mb-2 h-8 w-8 text-slate-300"/>No Talent Pool members match these filters.</div>:<div className="overflow-x-auto"><table className="min-w-[1180px] w-full text-left"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr>{["Applicant","Category","Roles / Skills","Priority","Owner","Review","Next Review","Actions"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{talent.map(x=>{const id=idOf(x);const review=x.talentPool.reviewStatus||(x.talentPool.active?"not_scheduled":"inactive");return <tr key={id||x.applicantCode} className="align-top"><td className="px-4 py-4"><button onClick={()=>id&&void onOpenApplicant?.(id)} className="text-left font-semibold text-slate-900 hover:text-blue-700">{x.identity?.fullName||"Unnamed Applicant"}<div className="text-xs font-normal text-slate-400">{x.applicantCode||id}</div></button></td><td className="px-4 py-4 text-sm">{x.category?.name||"Uncategorized"}</td><td className="px-4 py-4 text-xs text-slate-600">{[...(x.talentPool.roles||[]),...(x.skills?.primaryTechnical||[])].slice(0,6).join(" · ")||"—"}</td><td className="px-4 py-4 text-sm">{cap(x.talentPool.priority)}</td><td className="px-4 py-4 text-sm">{x.talentPool.ownerId||"Unassigned"}</td><td className="px-4 py-4 text-sm"><div>{cap(review)}</div><div className="text-xs text-slate-400">Last: {fmt(x.talentPool.lastReviewedAt)}</div></td><td className="px-4 py-4 text-sm">{fmt(x.talentPool.nextReviewAt)}</td><td className="px-4 py-4"><div className="flex min-w-[300px] flex-wrap gap-2"><button onClick={()=>id&&void onOpenApplicant?.(id)} className="flex items-center gap-1 rounded-lg border px-2 py-1 text-xs"><Eye className="h-3 w-3"/>View</button>{x.talentPool.active?<><button onClick={()=>void edit(x)} className="rounded-lg border border-blue-200 bg-blue-50 px-2 py-1 text-xs">Edit</button><button onClick={()=>id&&window.confirm("Mark review completed?")&&void act(()=>completeApplicantTalentPoolReview(id))} className="rounded-lg border border-emerald-200 bg-emerald-50 px-2 py-1 text-xs">Review</button><button onClick={()=>void schedule(x)} className="rounded-lg border border-violet-200 bg-violet-50 px-2 py-1 text-xs">Schedule</button><button onClick={()=>id&&window.confirm("Remove from Talent Pool only? The Applicant profile will NOT be deleted.")&&void act(()=>removeApplicantFromTalentPool(id))} className="rounded-lg border border-rose-200 bg-rose-50 px-2 py-1 text-xs">Remove</button></>:<button onClick={()=>id&&void act(()=>restoreApplicantToTalentPool(id))} className="rounded-lg border border-emerald-200 bg-emerald-50 px-2 py-1 text-xs">Restore</button>}</div></td></tr>})}</tbody></table></div>}
    <div className="flex items-center justify-between border-t p-4 text-xs text-slate-500"><span>{pagination.total} records · Page {pagination.page} of {Math.max(pagination.pages,1)}</span><div className="flex gap-2"><button disabled={pagination.page<=1} onClick={()=>setQuery(q=>({...q,page:Math.max((q.page||1)-1,1)}))} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4"/></button><button disabled={pagination.page>=pagination.pages} onClick={()=>setQuery(q=>({...q,page:(q.page||1)+1}))} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></div></div></section>
  </div>;
}
