#!/usr/bin/env bash
# =============================================================================
#  omah-dashboard — project cleanup
#  Usage:  bash scripts/cleanup.sh           <- DRY RUN, deletes nothing
#          bash scripts/cleanup.sh --apply   <- actually deletes
#
#  NEVER touches: data/, .env, src/, node_modules/, package*.json
# =============================================================================
set -uo pipefail

APPLY=0
[ "${1:-}" = "--apply" ] && APPLY=1

TOTAL=0
say() { printf '  %s\n' "$1"; }

group() { echo; echo "=== $1 ==============================================="; }

kill_paths() {   # kill_paths <find-args...>
  local found
  found=$(eval "$1" 2>/dev/null)
  if [ -z "$found" ]; then say "(nothing)"; return; fi
  while IFS= read -r p; do
    [ -z "$p" ] && continue
    local sz
    sz=$(du -sk "$p" 2>/dev/null | cut -f1)
    TOTAL=$((TOTAL + ${sz:-0}))
    if [ "$APPLY" = "1" ]; then
      rm -rf "$p" && say "deleted   $p"
    else
      say "would rm  $p  (${sz:-0} KB)"
    fi
  done <<< "$found"
}

[ "$APPLY" = "1" ] && echo ">>> APPLYING — files will be deleted" \
                   || echo ">>> DRY RUN — nothing will be deleted (add --apply to run for real)"

group "1. Patch backups left by our fix scripts"
kill_paths "find . -not -path './node_modules/*' -not -path './.git/*' \( -name '*.bak' -o -name '*.bak2' -o -name '*.orig' \) -print"

group "2. Stale duplicate source folders"
kill_paths "find . -maxdepth 1 -type d -name 'backup-before-rebase' -print"

group "3. Typo / stray files"
kill_paths "find . -maxdepth 1 -name '.gitignor' -o -maxdepth 1 -name '.tmp' -o -maxdepth 1 -name 'fix-*.cjs' -print"

group "4. One-off setup notes (superseded — MongoDB is running)"
kill_paths "find . -maxdepth 1 \( -name 'MONGODB_*.md' -o -name 'MONGODB_*.txt' -o -name 'README_MONGODB.md' -o -name 'COMPLETE_SERVER_JS.md' -o -name 'SERVER_UPDATES.md' \) -print"

group "5. Build output (regenerated by npm run build)"
kill_paths "find . -maxdepth 2 -type d -name 'dist' -not -path './node_modules/*' -print"

group "6. Old dated backups — keeping the newest of each kind"
echo "  data-backup-* folders:"
kill_paths "ls -d data-backup-* 2>/dev/null | sort | head -n -1"
echo "  backup-mongo snapshots:"
kill_paths "ls -d backup-mongo/*/ 2>/dev/null | sort | head -n -1"

group "SUMMARY"
if [ "$APPLY" = "1" ]; then
  echo "  freed roughly $((TOTAL / 1024)) MB"
else
  echo "  would free roughly $((TOTAL / 1024)) MB"
  echo "  run again with --apply to delete"
fi
echo
echo "  NOT touched (on purpose): data/  .env  src/  node_modules/  package*.json"
